# Generated by Django 2.2.9 on 2020-09-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvimport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='contentType',
            field=models.CharField(choices=[('HTML', 'HTML'), ('TEXT', 'Plain Text')], default='HTML', max_length=4),
        ),
    ]
