# Generated by Django 4.1.2 on 2023-01-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.TextField()),
                ('image_filename', models.TextField()),
                ('status', models.CharField(choices=[('start', 'start'), ('metadata', 'metadata'), ('verified', 'verified'), ('queued', 'queued'), ('archived', 'archived'), ('tidied', 'tidied')], default='start', max_length=10000)),
                ('job', models.TextField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_detail', models.TextField()),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('transaction_date',),
            },
        ),
    ]
