# Generated by Django 4.1.2 on 2023-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merritt_archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('ok', 'ok'), ('deferred', 'deferred'), ('queued', 'queued'), ('archived', 'archived'), ('tidied', 'tidied')], default='start', max_length=10000),
        ),
    ]
